.PHONY: clean

clean:
	find . -name "*~" -delete
	find . -name ".opencode*" -exec rm -rf {} +
	find . -name ".pi*" -exec rm -rf {} +
	find . -name ".claude" -type d -exec rm -rf {} +
	find . -name ".bsp" -type d -exec rm -rf {} +
	find . -name ".scala-build" -type d -exec rm -rf {} +
